### PR TITLE
Add telegram two-side bridge 

### PR DESCRIPTION
**Pull request by LionZXY**

### CODE REVIEW

**Comment by Tych0n** [comment]
Hi, @LionZXY ! Could you please tell how can I build your fork? I followed the path: git clone ..., cd ..., ./gradlew build and faced error `gradle/wrapper/gradle-wrapper.properties does not exist`.

**Comment by LionZXY** [comment]
Oops.  You can fix it with 
`gradle wrapper`

**Comment by LionZXY** [comment]
Or wait when i release my fork and remake this mod

**Comment by Tych0n** [comment]
@LionZXY sorry, i think i'm missing some specific moves, because i'm trying to build java repo for the first time. But `gradle wrapper` fails with:

    FAILURE: Build failed with an exceprion
    * Where:
    Build file '.../build.gradle' line 10
    * What went wrong:
    A problem occured evaluating root project 'TelegramIntegration'.
    > org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputs;

I saved `--scan` results [here](https://scans.gradle.com/s/ts7iib6gmoy3w).

**Comment by Tych0n** [comment]
Ok, shame on me. Some googling and with the help of https://github.com/athrane/bassebombecraft/issues/352 and `./gradlew jar` I was able to create `TelegramIntegration/build/libs/telegramintegration-1.12-1.1.0.jar`. But using it with `forge-1.12.2-14.23.5.2847-universal.jar` resulted in error:

    java.lang.NoSuchMethodError: 
        net.minecraft.util.StringUtils.isNullOrEmpty(Ljava/lang/String;)Z
            at mod.upcraftlp.telegramintegration.Main.preInit(Main.java:56) ~[Main.class:?]

**Comment by LionZXY** [comment]
I looked at the mod and quality of the code. It’s easier to rewrite everything from scratch and publish with my name. I see no reason to edit this PR

**Comment by LionZXY** [comment]
You can build from https://github.com/LionZXY/TelegramIntegration/tree/build/dirtyhack

**Comment by LionZXY** [comment]
Github: https://github.com/glitchless/MinecraftTelegramBridge
CurseForge: https://www.curseforge.com/minecraft/mc-mods/telegram-bridge

**Pull request closed without merging**
